### ISSUE TITLE
handle no role in contributors

### ISSUE THREAD

**Issue by dennisangemi** [dennisangemi/frictionless2md#28]
Input

```yaml
contributors:
  - title: Chiara Adornetto
    email: balbla@google.it
  - title: Dennis Angemi
    email: balbla@google.it
  - title: Carlo Canepa
    email: balbla@google.it
  - title: Moreno Colaiacovo
    email: balbla@google.it
  - title: Alice Nicole Ginosa
    email: balbla@google.it
  - title: Angelo Gulina
    email: balbla@google.it
  - title: Vittorio Nicoletta
    email: balbla@google.it
  - title: Lorenzo Ruffino
    email: balbla@google.it
```

Output:

## 👥 Contributors
| Name | Role | Email |
| --- | --- | --- |
| Chiara Adornetto | null | balbla@google.it |
| Dennis Angemi | null | balbla@google.it |
| Carlo Canepa | null | balbla@google.it |
| Moreno Colaiacovo | null | balbla@google.it |
| Alice Nicole Ginosa | null | balbla@google.it |
| Angelo Gulina | null | balbla@google.it|
| Vittorio Nicoletta | null | balbla@google.it |
| Lorenzo Ruffino | null | balbla@google.it |

## Actions
- Se `contributors` contiene almeno un `role` allora bisogna creare la colonna `role`, aggiungere la value se presente, mettere stringa vuota al posto di null
- Se `contributors` non contiene `role` non fare nulla
