### ISSUE TITLE
handle no title or description for a field

### ISSUE THREAD

**Issue by dennisangemi** [dennisangemi/frictionless2md#29]
Avoid printing `null`

Related issue: https://github.com/dennisangemi/frictionless2md/issues/3

Input:
```yaml
  - path: data/press.csv
    name: press
    profile: tabular-data-resource
    scheme: file
    format: csv
    hashing: md5
    encoding: utf-8
    schema:
      fields:
        - name: id
          type: integer
        - name: post_id
          type: integer
          title: Post ID
        - name: url
          title: Post URL
          type: string
          format: uri
        - name: post_title
          type: string
        - name: post_subtitle
          type: string
        - name: type
          title: Post type
          type: string
          constraints:
            enum:
              - articolo
              - fact-checking
        - name: source
          type: string
          title: Post source
        - name: subject
          type: string
        - name: list
          type: string
        - name: subject_id
          type: integer
        - name: list_id
          type: integer
```

Ouput:
### 📄 [press](data/press.csv)
- Path: `data/press.csv`
- Encoding: `utf-8`

| Field | Type | Description | Example |
| --- | --- | --- | --- |
| id | integer | null | 1 |
| post_id | integer | Post ID | 1 |
| url | string | Post URL | https://pagellapolitica.it/articoli/guida-sondaggi-politici |
| post_title | string | null | Guida alla lettura dei sondaggi politic |
| post_subtitle | string | null | Nelle prossime settimane ne vedremo decine: le informazioni utili per 
saperli leggere |
| type | string | Post type | articolo |
| source | string | Post source | Pagella Politica |
| subject | string | null |  |
| list | string | null |  |
| subject_id | integer | null |  |
| list_id | integer | null |  |
