### ISSUE TITLE
delimiter key non riconosciuta

### ISSUE THREAD

**Issue by dennisangemi** [dennisangemi/frictionless2md#42]
ottengo:

>⚠️  Warning: Delimiter key not found for sicilia_dighe_volumi
Delimiter info will not be added to METADATA.md
⚠️  Warning: Delimiter key not found for sicilia_dighe_anagrafica
Delimiter info will not be added to METADATA.md
⚠️  Warning: Delimiter key not found for italia_grandi_dighe_anagrafica
Delimiter info will not be added to METADATA.md
⚠️  Warning: Delimiter key not found for sicilia_dighe_competenza_utd_palermo

ma 

```yaml
resources:
  - name: sicilia_dighe_volumi
    description: Volumi invasati nelle dighe della Sicilia. Tabella estratta dai file PDF rilasciati dalla Regione Siciliana (vd. sources)
    sources: 
      - title: Volumi invasati nelle dighe della Sicilia (Regione Siciliana)
        description: Pagina web della Regione Siciliana che raccoglie documenti PDF contenenti le serie storiche dei volumi invasati nelle dighe della Sicilia
        path: https://www.regione.sicilia.it/istituzioni/regione/strutture-regionali/presidenza-regione/autorita-bacino-distretto-idrografico-sicilia/siti-tematici/risorse-idriche/volumi-invasati-nelle-dighe-della-sicilia
    type: table
    path: risorse/sicilia_dighe_volumi.csv
    scheme: file
    format: csv
    mediatype: text/csv
    encoding: utf-8
    dialect:
      delimiter: ","
```
